# Generated by Django 5.2.1 on 2025-05-12 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('year_of_experience', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('posted_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usertype', models.CharField(choices=[('option1', 'User'), ('option2', 'Company')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('appliedAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending Review', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pages.job')),
            ],
        ),
    ]
