# Generated by Django 5.2.1 on 2025-05-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_savedjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedJob',
        ),
    ]
