# Generated by Django 5.2.1 on 2025-05-14 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_savedjob'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pages.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='pages.job'),
        ),
    ]
