# Generated by Django 5.2.1 on 2025-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_application_cv_remove_application_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
